# Generated by Django 3.2.4 on 2021-06-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210608_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.companymodel')),
            ],
        ),
        migrations.CreateModel(
            name='HardwareModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.projectmodel')),
                ('tester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.testermodel')),
            ],
        ),
    ]
