# Generated by Django 3.2.4 on 2021-06-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210608_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwaremodel',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('to be delivered', 'To be delivered'), ('delivered', 'Delivered'), ('returning', 'Returning'), ('returned', 'Returned'), ('kept', 'Kept')], default='unassigned', max_length=15),
        ),
    ]
