# Generated by Django 3.2.4 on 2021-06-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_hardwaremodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='name',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='hardwaremodel',
            name='name',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='hardwaremodel',
            name='status',
            field=models.CharField(choices=[('Unassigned', 'Unassigned'), ('To be delivered', 'To be delivered'), ('Delivered', 'Delivered'), ('Returning', 'Returning'), ('Returned', 'Returned'), ('Kept', 'Kept')], default='Unassigned', max_length=15),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='name',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='testermodel',
            name='name',
            field=models.TextField(default=None),
        ),
    ]
